### ISSUE TITLE
I can’t get any validation code or link from beatsaber

### ISSUE THREAD

**Issue by Elspeth1** [mindleaving/beatsabertools#2]
After register on Beatsaber
I need to validation of my email
I checked my email and all empty.
Spam is also empty. So I couldn’t upload my music I need help!

**Comment by caffeine239** [comment]
i dont see why this issue is here, this repo is for a program that generates files from mp3s. There is no registrations.

**Comment by mindleaving** [comment]
Hi @Elspeth1. I'm not associated with Beatsaber and cannot help you with that issue :)

**Comment by Elspeth1** [comment]
I am so sorry about finding the wrong place
