### ISSUE TITLE
Support for Beat Saber 1.1?

### ISSUE THREAD

**Issue by voehl** [mindleaving/beatsabertools#3]
Hey,

first of all: Thanks for your project!

I was just testing the latest build and it seems the generated levels are not compatible with the latest beat saber version. Possibly because the tool only creates the required json files, but not the .dat files.

I was trying to look into it myself but I am struggling with getting the project to compile on my machine (because I have no experience with .NET).

Since the last commit is about an year old, I was wondering if you are still planning to maintain this project in the future?

Thanks and best regards

**Comment by voehl** [comment]
This is the new level format: https://gist.github.com/MCJack123/892b936ef0d18da43ab2764ba97402be

**Comment by mindleaving** [comment]
Sorry for the late reply. The project is not maintained.
